export const RegisterConfig = [
  {
    questionid: 1,
    questionname: "Employee_ID_Number",
    questionvalue: "",
    question: "Employee Id",
    questiontype: "Number",
    required: true,
  },
  {
    questionid: 2,
    questionname: "Password",
    questionvalue: "",
    question: "Password",
    questiontype: "Password",
    required: true,
  },
  {
    questionid: 3,
    questionname: "Re_Type_Password",
    questionvalue: "",
    question: "Re-Type Password",
    questiontype: "Password",
    required: true,
  },
  {
    questionid: 4,
    questionname: "First_Name",
    question: "First Name",
    questiontype: "Text",
    required: true,
  },
  {
    questionid: 5,
    questionname: "Middle_Name",
    question: "Middle Name",
    questiontype: "Text",
    required: false,
  },
  {
    questionid: 6,
    questionname: "Last_Name",
    question: "Last Name",
    questiontype: "Text",
    required: false,
  },
  {
    questionid: 7,
    questionname: "Date_of_Birth",
    question: "Date of Birth",
    questiontype: "Date",
    required: false,
  },
  {
    questionid: 8,
    questionname: "Phone_Number",
    question: "Phone Number",
    questiontype: "Number",
    required: false,
  },
  {
    questionid: 9,
    questionname: "Address",
    question: "Address",
    questiontype: "Textarea",
    required: false,
  },
  {
    questionid: 10,
    questionname: "Postal_Code",
    question: "Postal Code",
    questiontype: "Number",
    required: false,
  },
  {
    questionid: 11,
    questionname: "Qualification",
    question: "Qualification",
    questiontype: "Text",
    required: false,
  },
  {
    questionid: 12,
    questionname: "Total_Experience",
    question: "Total Experience",
    questiontype: "Number",
    required: false,
  },
  {
    questionid: 13,
    questionname: "Start_Date_Date",
    question: "Start Date",
    questiontype: "Date",
    required: false,
  },
  {
    questionid: 14,
    questionname: "End_Date_Date",
    question: "End Date",
    questiontype: "Date",
    required: false,
  },
  {
    questionid: 15,
    questionname: "Type_of_Employee",
    question: "Type of employee",
    questiontype: "Dropdown",
    required: false,
    questionoption: [
      { optionid: 1, optionvalue: "Permanent" },
      { optionid: 2, optionvalue: "Part-Time" },
    ],
  },
  {
    questionid: 16,
    questionname: "Designation",
    question: "Designation",
    questiontype: "Dropdown",
    required: true,
    questionoption: [
      { optionid: 1, optionvalue: "Developer" },
      { optionid: 2, optionvalue: "Tester" },
      { optionid: 3, optionvalue: "Manager" },
      { optionid: 4, optionvalue: "QA" },
    ],
  },
  {
    questionid: 17,
    questionname: "Gender",
    question: "Gender",
    questiontype: "Dropdown",
    required: false,
    questionoption: [
      { optionid: 1, optionvalue: "Male" },
      { optionid: 2, optionvalue: "Female" },
      { optionid: 3, optionvalue: "Other" },
    ],
  },
  {
    questionid: 18,
    questionname: "Marital_Status",
    question: "Marital Status",
    questiontype: "Dropdown",
    required: false,
    questionoption: [
      { optionid: 1, optionvalue: "Married" },
      { optionid: 2, optionvalue: "Unmarried" },
    ],
  },
];
